version: "3.8"
services:
  api:
    container_name: proxy
    image: node:15.3.0-alpine
    command: "yarn start:dev"
    working_dir: /opt/api
    ports:
      - "8080:8080"
    volumes:
      - ./server:/opt/api
    links:
      - redis
      - mongo
    environment:
      MONGO_HOSTNAME: "mongo"
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
  mongo:
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: "mongo_admin"
      MONGO_INITDB_ROOT_PASSWORD: "mongo_secret"
      MONGO_INITDB_DATABASE: "default_database"
    image: mongo
    volumes:
      - ./server/scripts/db/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./server/data/mongo:/data/db
    ports:
      - "27017:27017"
