version: "3.8"
services:
  api:
    container_name: proxy
    image: node:15.3.0-alpine
    command: "yarn start:dev"
    working_dir: /opt/api
    ports:
      - "8080:8080"
    volumes:
      - ./server:/opt/api
    links:
      - redis
      - mongo
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
  mongo:
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "secret"
      MONGO_INITDB_DATABASE: "database"
    image: mongo
    ports:
      - "27017:27017"
